"""empty message

Revision ID: fce2b5f0264f
Revises: 6e7f6ac0d2d1
Create Date: 2022-12-17 18:18:27.479129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce2b5f0264f'
down_revision = '6e7f6ac0d2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_profile_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_profile_img')
    # ### end Alembic commands ###
